### ISSUE TITLE
可否接入其他登录方式和支付方式

### ISSUE THREAD

**Issue by somnifex** [gptlink/gptlink#10]
微信申请需要营业执照

**Comment by overtrue** [comment]
登录好说，但是在国内，几乎没有不需要营业执照的支付渠道

**Comment by somnifex** [comment]
> 登录好说，但是在国内，几乎没有不需要营业执照的支付渠道

是这样的，但是对于个人来说，如果我只想把系统和身边的人使用，那么支付宝当面付就可以满足需求，如果大规模运营肯定是需要合法化

**Comment by hiyouli** [comment]
建议增加1、其他登录方式。2、其他支付方式。
否者不会有大面积使用场景。

**Comment by overtrue** [comment]
> 

明白，安排！

**Comment by loongwind** [comment]
可以增加卡密充值的方式，卡密就可以通过其他方式进行出售

**Comment by somnifex** [comment]
对企业来说支付挺简单，对个人目前基本也就3种途径，1、支付宝当面付   2、使用第三方发卡平台 3、自己写脚本接入通知监控，一般2、3都会做成发卡的方式，使用兑换码兑换

**Comment by 0daynick** [comment]
用户名密码登录与线下支付已发布。可以获取新版体验
