### ISSUE TITLE
登录问题

### ISSUE THREAD

**Issue by xqa** [gptlink/gptlink#18]
能在后台配置用户的账号密码用于登录吗，微信那个好麻烦，还有弄网站信息登记表什么的

**Comment by 0daynick** [comment]
> 能在后台配置用户的账号密码用于登录吗，微信那个好麻烦，还有弄网站信息登记表什么的

已经在制作了，下一个版本就会发布。

**Comment by inroading** [comment]
下个版本大概什么时候发布啊

**Comment by 0daynick** [comment]
> 下个版本大概什么时候发布啊

预计1周左右，已经进入前后端联调的阶段了

**Comment by wu-clan** [comment]
一切准备就绪，到了微信登录那一堆直接劝退了，期待新版本

**Comment by 0daynick** [comment]
已经发布了新版本可以体验
