### ISSUE TITLE
请对Microsoft Azure OpenAI的支持

### ISSUE THREAD

**Issue by 6bf3803cb456** [gptlink/gptlink#19]
如题，Azure OpenAI更适合商用，也适合国内申请。毕竟支付渠道在那摆着，望支持。还有输入敏感词词库，过滤发送和接收。国内嘛，要符合规定。建议将套餐以2个维度：时间+次数的方式创建，更好的做细分市场。

**Comment by 0daynick** [comment]
Azure OpenAI接入，关键词过滤没问题，

时间+次数 目前没有较好的叠加方式并同时与现有套餐兼容，可以提供相对完整的方案评估看是否可行。

**Comment by somnifex** [comment]
> Azure OpenAI接入，关键词过滤没问题，
> 
> 时间+次数 目前没有较好的叠加方式并同时与现有套餐兼容，可以提供相对完整的方案评估看是否可行。

可以看看oneapi项目，我现在后端基本都是用的他，渠道管理跟应用分离了。https://github.com/songquanpeng/one-api

**Comment by 0daynick** [comment]
> > Azure OpenAI接入，关键词过滤没问题，
> > 时间+次数 目前没有较好的叠加方式并同时与现有套餐兼容，可以提供相对完整的方案评估看是否可行。
> 
> 可以看看oneapi项目，我现在后端基本都是用的他，渠道管理跟应用分离了。https://github.com/songquanpeng/one-api

做渠道支持并不难，麻烦的是业务功能的支持。

**Comment by somnifex** [comment]
> > > Azure OpenAI接入，关键词过滤没问题，
> > > 时间+次数 目前没有较好的叠加方式并同时与现有套餐兼容，可以提供相对完整的方案评估看是否可行。
> > 
> > 
> > 可以看看oneapi项目，我现在后端基本都是用的他，渠道管理跟应用分离了。https://github.com/songquanpeng/one-api
> 
> 做渠道支持并不难，麻烦的是业务功能的支持。

是啊，oneapi后端支持了业务功能，可以用于参考

**Comment by 0daynick** [comment]
关于后续 azure openai 的支持，关注 https://github.com/gptlink/gptlink/issues/50
