### ISSUE TITLE
添加更多用户管理功能

### ISSUE THREAD

**Issue by somnifex** [gptlink/gptlink#25]
为用户提供注销选项，
超级管理员后台可以对用户进行停用和删除
增加管理员权限，可以设定管理员

**Comment by 0daynick** [comment]
权限管理的相关运营需求各不相同，现在不考虑进行延伸。

**Comment by somnifex** [comment]
> 

是的每个站都不一样，个人进行二开是合适的，用户注销和管理员能够删除用户或者暂停用户我认为是公共需求

**Comment by 0daynick** [comment]
现在只能优先满足缺陷的修复，开发资源不够的，如果要参与进来一起贡献可以进群联系。
