### ISSUE TITLE
GPT回答不实时传输 

### ISSUE THREAD

**Issue by mctds** [gptlink/gptlink#30]
环境：Docker Compose
版本：线上最新版
问题：对话中，GPT回复不实时传输，看响应正常，但是输出内容的时候一次性输出（如下视频）

https://github.com/gptlink/gptlink/assets/77908808/3ddcfda4-3d5b-4662-8baf-4496ef7b26be

JS报错如图
![20230604095623](https://github.com/gptlink/gptlink/assets/77908808/88546eb8-3516-47ba-b0b5-3616b5e88b12)

**Comment by 0daynick** [comment]
问题没有复现，检查是否因为开启waf ，或cdn中开启压缩导致。

**Comment by mctds** [comment]
> 问题没有复现，检查是否因为开启waf ，或cdn中开启压缩导致。

没有开CDN，waf也正常没有异常情况。

**Comment by 0daynick** [comment]
可以关闭waf后再试。

cdn-cgi/challenge-pl..ipts/invisible.js 异常的部分不是项目文件。

**Comment by mctds** [comment]
> 可以关闭waf后再试。
> 
> cdn-cgi/challenge-pl..ipts/invisible.js 异常的部分不是项目文件。

又测试了一下，无报错，但是不实时传输的问题依旧。

**Comment by zlazlazl** [comment]
> > 可以关闭waf后再试。
> > cdn-cgi/challenge-pl..ipts/invisible.js 异常的部分不是项目文件。
> 
> 又测试了一下，无报错，但是不实时传输的问题依旧。

一种可能原因是经过 Nginx 反向代理，开启了 buffer，则 Nginx 会尝试从后端缓冲一定大小的数据再发送给浏览器。请尝试在反代参数后添加 proxy_buffering off;然后重载 Nginx。其他 web server 配置同理。
