### ISSUE TITLE
模型与角色管理/后台套餐管理等小问题

### ISSUE THREAD

**Issue by Lcking** [gptlink/gptlink#31]
#### 模型与角色管理
1. 只有新增模型角色没有删除模型角色的选项；

#### 后台套餐管理
1. 如果后台套餐过多，排列会有样式错乱

**Comment by Pingozhu** [comment]
模型角色是否可以指定给特定的会员使用？

**Comment by 0daynick** [comment]
> 模型角色是否可以指定给特定的会员使用？

暂时没有计划，可以自行考虑实现。
