### ISSUE TITLE
关注公众号的任务是否可以打开

### ISSUE THREAD

**Issue by Pingozhu** [gptlink/gptlink#34]
我们是否可以考虑打开关注公众号的任务呢？目前，我们面临的挑战是，网页端用户离开后很难召回，因为缺乏一个与用户建立持续联系的链接。很多用户在体验了我们的服务后，难以找到再次访问的入口，这增加了拓展用户的成本。为了实现更高的用户活跃度和价值输出，我们需要持续地提醒用户使用我们的服务。这有这样我们才能不断努力提高用户的参与度和价值产出。

**Comment by 0daynick** [comment]
没有这个功能，开源版本与体验的版本已经是两套系统了。

**Comment by Pingozhu** [comment]
是否可以在个人中心底部自定义一个图片（公众号关注码）？谢谢了

**Comment by 0daynick** [comment]
关注公众号的功能可以考虑实现，不过没有这么快进行。个人中心底部自定义内容的功能暂时没有计划。

**Comment by 0daynick** [comment]
> 是否可以在个人中心底部自定义一个图片（公众号关注码）？谢谢了

关注公众号的功能可以考虑实现，不过没有这么快进行。个人中心底部自定义内容的功能暂时没有计划。
