### ISSUE TITLE
使用openai的api会提示出错

### ISSUE THREAD

**Issue by srxh-max** [gptlink/gptlink#36]
“好像出错了，请稍后再试。”

**Comment by 0daynick** [comment]
根据服务器相关日志排查问题。

https://github.com/gptlink/gptlink/blob/master/docs/FAQ.md#%E5%A6%82%E4%BD%95%E6%9F%A5%E7%9C%8B%E6%9C%8D%E5%8A%A1%E6%97%A5%E5%BF%97

**Comment by 0daynick** [comment]
排查思路参考文档中注意事项部分：https://github.com/gptlink/gptlink/blob/master/docs/FAQ.md#%E5%A6%82%E4%BD%95%E9%85%8D%E7%BD%AE%E4%BD%BF%E7%94%A8-openai-%E6%8F%90%E4%BE%9B%E7%9A%84%E6%8E%A5%E5%8F%A3
