### ISSUE TITLE
请问如何修改chatgpt请求的版本

### ISSUE THREAD

**Issue by srxh-max** [gptlink/gptlink#38]
显示的日志的时间时区如何设置

**Comment by 0daynick** [comment]
已设置默认时区为上海

https://github.com/gptlink/gptlink/commit/4b76b128b2e58ddba07e85ff93422fddf5be0857

**Comment by 0daynick** [comment]
关于修改chatgpt请求版本已在新版本中支持

https://github.com/gptlink/gptlink/releases/tag/v1.1.1
