### ISSUE TITLE
报错No such file or directory

### ISSUE THREAD

**Issue by xinmans** [gptlink/gptlink#39]
SQLSTATE[HY000] [2002] No such file or directory (SQL: select * from `config` where (`type` = 1) limit 1)

**Comment by 0daynick** [comment]
确认数据库可链接，如果可正常连接重启gptlink容器即可。

**Comment by 0daynick** [comment]
参考

https://github.com/gptlink/gptlink/blob/master/docs/FAQ.md#%E6%95%B0%E6%8D%AE%E8%A1%A8%E6%B2%A1%E6%9C%89%E6%88%90%E5%8A%9F%E5%88%9B%E5%BB%BA
