### ISSUE TITLE
在微信浏览器中，如果对话比较长，聊天框打字会变卡

### ISSUE THREAD

**Issue by 18601673727** [gptlink/gptlink#40]
用微信打开前端页面，与gpt随便聊一下，当页面上字数比较多的时候，再进行输入就会卡顿

**Comment by 0daynick** [comment]
可以提供一下 浏览器的版本，访问设备的系统版本。 

或者使用其他设备访问，看是不是设备的问题。

**Comment by 18601673727** [comment]
多种手机都这样 因为是来自用户的反馈 我个人是android 可以重现 
浏览器版本不清楚是微信内置的

**Comment by 0daynick** [comment]
> 多种手机都这样 因为是来自用户的反馈 我个人是android 可以重现 浏览器版本不清楚是微信内置的

那可以提供一下使用的手机的品牌和型号，我们暂时无法复现这个问题。

**Comment by 18601673727** [comment]
大概是我没说清楚 随便找个安卓手机 安装最新版微信 打开H5 跟GPT聊上一两屏的对话 后面再打字就会卡 包括删除（backsapce） 感觉像是js进程被阻塞 绑了太多event的那种感觉

**Comment by 0daynick** [comment]
> 大概是我没说清楚 随便找个安卓手机 安装最新版微信 打开H5 跟GPT聊上一两屏的对话 后面再打字就会卡 包括删除（backsapce） 感觉像是js进程被阻塞 绑了太多event的那种感觉

复现不了，你加群提供一个录制的视频吧。
