### ISSUE TITLE
请问用户界面可以让用户自己决定用什么模型吗？

### ISSUE THREAD

**Issue by linxin6** [gptlink/gptlink#44]

**Comment by 0daynick** [comment]
目前的设计比较难兼容这种方式。

**Comment by linxin6** [comment]
我有注意到大佬您在源码里设计了用户自定的模型的。既然如此那困难在哪里呢？

**Comment by 0daynick** [comment]
> 我有注意到大佬您在源码里设计了用户自定的模型的。既然如此那困难在哪里呢？

计费上不好支持。

**Comment by linxin6** [comment]
> 

明白了，感谢。最后想请问后面有计划开发这个功能吗？

**Comment by 0daynick** [comment]
> > 
> 
> 明白了，感谢。最后想请问后面有计划开发这个功能吗？

现阶段暂时可能支持不到，后续有合适的方案可以考虑
