### ISSUE TITLE
连接数据库错误

### ISSUE THREAD

**Issue by smilesmallbird** [gptlink/gptlink#47]
exception {"req":{"url":"http://114.114.114.114:6653/chat"},"url":"GET http://127.0.0.1:9503/wechat/jssdk?url=http%3A%2F%2F114.114.114.114%3A6653%2Fchat","message":"SQLSTATE[HY000] [2002] Connection refused (SQL: select * from `config` where (`type` = 1) limit 1)[1088] in /app/gptserver/vendor/hyperf/database/src/Connection.php","trace":

**Comment by 0daynick** [comment]
常见文档文档中有写相关的处理。

https://github.com/gptlink/gptlink/blob/master/docs/FAQ.md#%E6%95%B0%E6%8D%AE%E8%A1%A8%E6%B2%A1%E6%9C%89%E6%88%90%E5%8A%9F%E5%88%9B%E5%BB%BA
