### ISSUE TITLE
能否添加对Azuer OpenAi的支持

### ISSUE THREAD

**Issue by cdmc00** [gptlink/gptlink#50]
能否添加对Azuer OpenAi的支持

**Comment by 0daynick** [comment]
> 能否添加对Azuer OpenAi的支持

可以支持，不过目前没有可以调试的 key。如果愿意提供测试的key，可以加群联系我。

**Comment by cdmc00** [comment]
> 

加群了，直接联系群主还是你联系我呢？  我是那个凌

**Comment by 0daynick** [comment]
> > 
> 
> 加群了，直接联系群主还是你联系我呢？ 我是那个凌

重新添加群主，备注一下

**Comment by cdmc00** [comment]
> > > 
> > 
> > 
> > 加群了，直接联系群主还是你联系我呢？ 我是那个凌
> 
> 重新添加群主，备注一下

加了加了，等通过
