### ISSUE TITLE
在微信端打开能否根据是否配置公众号登录从而判断支付类型

### ISSUE THREAD

**Issue by fastdragon18** [gptlink/gptlink#52]
在微信端打开能否根据是否配置公众号登录从而判断支付类型，现在在非微信端打开是扫码支付，在微信内打开支付提示需要openid 但是我没有配置公众号 使用无法调用支付

**Comment by 0daynick** [comment]
微信内打开也完不成扫码支付的操作呀。

**Comment by fastdragon18** [comment]
> 微信内打开也完成不了扫码支付的操作呀。

那可不可以加一个H5支付呢，因为现在大部分用户都是在微信打开

**Comment by 0daynick** [comment]
> > 微信内打开也完成不了扫码支付的操作呀。
> 
> 那可不可以加一个H5支付呢，因为现在大部分用户都是在微信打开

微信打开的只能走公众号JSAPI支付。h5是在手机浏览器跳转的
