### ISSUE TITLE
通过域名访问时，流失传输有问题

### ISSUE THREAD

**Issue by yigeimuya** [gptlink/gptlink#54]
1、iP+端口访问时，流式传输没有问题，响应比较快；
2、域名访问时，可以流式传输但是明显有卡顿感，如果是长短文字输出，比如写文字，回复内容会突然变多或者变少。

测试卸载nginx，http协议，都还是会存在一样的问题，同一设备同一浏览器。

移动端基本每次都可以复现，PC端相对好一些。

https://github.com/gptlink/gptlink/assets/129144058/1e8bf08f-79b7-4670-826b-acec4edd67ec

**Comment by yigeimuya** [comment]
通过ip+端口访问基本不会存在这个情况，并且流式传输也更流畅

**Comment by westeast** [comment]
同遇到过这种情况，一直闪的，我是在pc上，我看了控制台，是闪的时间报json解析错误

**Comment by jacywy** [comment]
同遇到过这种情况，还以为是浏览器兼容问题，没测试过其他的

**Comment by 0daynick** [comment]
后续会使用  https://github.com/gptlink/gptlink-web 项目来替换 gptweb 的部分完成这些优化。
