### ISSUE TITLE
希望增加验证码接口（图形或者拖拽式）

### ISSUE THREAD

**Issue by BenbenJ0** [gptlink/gptlink#55]
使用单纯的账号密码登录 会存在被大量账号刷接口的问题。
比如：只开账号和密码登录，可以大量机器人注册 薅注册和分享的赠送次数
增加验证码可以使机器人绕过成本增加

**Comment by 0daynick** [comment]
明白，可以先考虑使用微信相关方式去登陆，后续会考虑引入验证机制。或者可以向仓库贡献代码完成这个需求。
