### ISSUE TITLE
希望增加apiKey轮询功能以及用于二开的发货接口

### ISSUE THREAD

**Issue by reinershir** [gptlink/gptlink#57]
目前只能配置一个openai Key很容易超过限制

另外希望能增加发货接口，用于对接自己的支付回调系统 

因为很多个人用户是没有营业执照的

**Comment by 0daynick** [comment]
目前的定位更倾向于企业用户去使用，个人用户的需求繁杂不统一，不好去兼容。如果你认为需要实现的功能比较通用，欢迎PR。
