### ISSUE TITLE
提个建议，微信扫码登录，改成微信扫码关注公众号登录

### ISSUE THREAD

**Issue by zlazlazl** [gptlink/gptlink#58]
用户体验也好，公众号粉丝数也好，双赢

**Comment by overtrue** [comment]
> 用户体验也好，公众号粉丝数也好，双赢

我要是看到哪家产品这么暴力，我直接放弃使用，还用户体验好呢……

**Comment by zlazlazl** [comment]
https://www.gaoding.com/
老哥实际体验下，用户第一次注册后，以后每次登录只需扫码，扫码后都不用点允许，就能登录

**Comment by overtrue** [comment]
> https://www.gaoding.com/
> 
> 老哥实际体验下，用户第一次注册后，以后每次登录只需扫码，扫码后都不用点允许，就能登录

我知道这个方式，我也实现过，但是用户反感的是：关注公众号。

很多人有洁癖，关注公众号意味着一堆垃圾推送的可能，很多人对这个行为很反感，我们的产品被投诉过多去掉了这个行为。

**Comment by zlazlazl** [comment]
> > https://www.gaoding.com/
> > 老哥实际体验下，用户第一次注册后，以后每次登录只需扫码，扫码后都不用点允许，就能登录
> 
> 我知道这个方式，我也实现过，但是用户反感的是：关注公众号。
> 
> 很多人有洁癖，关注公众号意味着一堆垃圾推送的可能，很多人对这个行为很反感，我们的产品被投诉过多去掉了这个行为。

原来如此
