### ISSUE TITLE
Mysql拒绝主机连接

### ISSUE THREAD

**Issue by Zqwater** [gptlink/gptlink#60]
SQLSTATE[HY000] [1130] Host '172.10.10.3' is not allowed to connect to this MySQL server (SQL: select `id`, `user_id`, `icon`, `name`, `prompt`, `status`, `sort`, `uses`, `likes`, `created_at`, `desc`, `source`, `type` from `chat_gpt_model` left join `chat_gpt_model_count` on `chat_gpt_model`.`id` = `chat_gpt_model_count`.`chat_gpt_model_id` where (`platform` = 1) and (`status` = 1) order by `sort` desc, `uses` desc, `created_at` desc limit 500)

**Comment by 0daynick** [comment]
检查 mysql 相关的设置，或检查 mysql 启动是否异常
