### ISSUE TITLE
回复中断问题

### ISSUE THREAD

**Issue by irol765** [gptlink/gptlink#63]
|#9 /app/gptserver/vendor/hyperf/async-queue/src/Process/ConsumerProcess.php(57): Hyperf\AsyncQueue\Driver\Driver->consume()
{#10 /app/gptserver/vendor/hyperf/process/src/AbstractProcess.php(134): Hyperf\AsyncQueue\Process\ConsumerProcess->handle()
#11 {main}
[WARNING] Get connection failed, try again. RedisException: Connection refused in /app/gptserver/vendor/hyperf/redis/src/RedisConnection.php:268

Stack trace:
U#0 /app/gptserver/vendor/hyperf/redis/src/RedisConnection.php(268): Redis->connect()
p#1 /app/gptserver/vendor/hyperf/redis/src/RedisConnection.php(117): Hyperf\Redis\RedisConnection->createRedis()
m#2 /app/gptserver/vendor/hyperf/redis/src/RedisConnection.php(91): Hyperf\Redis\RedisConnection->reconnect()
q#3 /app/gptserver/vendor/hyperf/pool/src/Connection.php(49): Hyperf\Redis\RedisConnection->getActiveConnection()
a#4 /app/gptserver/vendor/hyperf/redis/src/Redis.php(47): Hyperf\Pool\Connection->getConnection()
[#5 /app/gptserver/vendor/hyperf/redis/src/RedisProxy.php(32): Hyperf\Redis\Redis->__call()
o#6 /app/gptserver/vendor/hyperf/async-queue/src/Driver/RedisDriver.php(193): Hyperf\Redis\RedisProxy->__call()
y#7 /app/gptserver/vendor/hyperf/async-queue/src/Driver/RedisDriver.php(85): Hyperf\AsyncQueue\Driver\RedisDriver->move()
s#8 /app/gptserver/vendor/hyperf/async-queue/src/Driver/Driver.php(86): Hyperf\AsyncQueue\Driver\RedisDriver->pop()
|#9 /app/gptserver/vendor/hyperf/async-queue/src/Process/ConsumerProcess.php(57): Hyperf\AsyncQueue\Driver\Driver->consume()
{#10 /app/gptserver/vendor/hyperf/process/src/AbstractProcess.php(134): Hyperf\AsyncQueue\Process\ConsumerProcess->handle()
#11 {main}
m[ERROR] RedisException: Connection refused in /app/gptserver/vendor/hyperf/redis/src/RedisConnection.php:268

Stack trace:
U#0 /app/gptserver/vendor/hyperf/redis/src/RedisConnection.php(268): Redis->connect()
p#1 /app/gptserver/vendor/hyperf/redis/src/RedisConnection.php(117): Hyperf\Redis\RedisConnection->createRedis()
m#2 /app/gptserver/vendor/hyperf/redis/src/RedisConnection.php(91): Hyperf\Redis\RedisConnection->reconnect()
q#3 /app/gptserver/vendor/hyperf/pool/src/Connection.php(54): Hyperf\Redis\RedisConnection->getActiveConnection()
a#4 /app/gptserver/vendor/hyperf/redis/src/Redis.php(47): Hyperf\Pool\Connection->getConnection()
[#5 /app/gptserver/vendor/hyperf/redis/src/RedisProxy.php(32): Hyperf\Redis\Redis->__call()
o#6 /app/gptserver/vendor/hyperf/async-queue/src/Driver/RedisDriver.php(193): Hyperf\Redis\RedisProxy->__call()
y#7 /app/gptserver/vendor/hyperf/async-queue/src/Driver/RedisDriver.php(85): Hyperf\AsyncQueue\Driver\RedisDriver->move()
s#8 /app/gptserver/vendor/hyperf/async-queue/src/Driver/Driver.php(86): Hyperf\AsyncQueue\Driver\RedisDriver->pop()
|#9 /app/gptserver/vendor/hyperf/async-queue/src/Process/ConsumerProcess.php(57): Hyperf\AsyncQueue\Driver\Driver->consume()
{#10 /app/gptserver/vendor/hyperf/process/src/AbstractProcess.php(134): Hyperf\AsyncQueue\Process\ConsumerProcess->handle()
#11 {main}
[WARNING] Get connection failed, try again. RedisException: Connection refused in /app/gptserver/vendor/hyperf/redis/src/RedisConnection.php:268

Stack trace:
U#0 /app/gptserver/vendor/hyperf/redis/src/RedisConnection.php(268): Redis->connect()
p#1 /app/gptserver/vendor/hyperf/redis/src/RedisConnection.php(117): Hyperf\Redis\RedisConnection->createRedis()
m#2 /app/gptserver/vendor/hyperf/redis/src/RedisConnection.php(91): Hyperf\Redis\RedisConnection->reconnect()
q#3 /app/gptserver/vendor/hyperf/pool/src/Connection.php(49): Hyperf\Redis\RedisConnection->getActiveConnection()
a#4 /app/gptserver/vendor/hyperf/redis/src/Redis.php(47): Hyperf\Pool\Connection->getConnection()
[#5 /app/gptserver/vendor/hyperf/redis/src/RedisProxy.php(32): Hyperf\Redis\Redis->__call()
o#6 /app/gptserver/vendor/hyperf/async-queue/src/Driver/RedisDriver.php(193): Hyperf\Redis\RedisProxy->__call()
y#7 /app/gptserver/vendor/hyperf/async-queue/src/Driver/RedisDriver.php(85): Hyperf\AsyncQueue\Driver\RedisDriver->move()
s#8 /app/gptserver/vendor/hyperf/async-queue/src/Driver/Driver.php(86): Hyperf\AsyncQueue\Driver\RedisDriver->pop()
|#9 /app/gptserver/vendor/hyperf/async-queue/src/Process/ConsumerProcess.php(57): Hyperf\AsyncQueue\Driver\Driver->consume()
{#10 /app/gptserver/vendor/hyperf/process/src/AbstractProcess.php(134): Hyperf\AsyncQueue\Process\ConsumerProcess->handle()
#11 {main}
m[ERROR] RedisException: Connection refused in /app/gptserver/vendor/hyperf/redis/src/RedisConnection.php:268

Stack trace:
U#0 /app/gptserver/vendor/hyperf/redis/src/RedisConnection.php(268): Redis->connect()
p#1 /app/gptserver/vendor/hyperf/redis/src/RedisConnection.php(117): Hyperf\Redis\RedisConnection->createRedis()
m#2 /app/gptserver/vendor/hyperf/redis/src/RedisConnection.php(91): Hyperf\Redis\RedisConnection->reconnect()
q#3 /app/gptserver/vendor/hyperf/pool/src/Connection.php(54): Hyperf\Redis\RedisConnection->getActiveConnection()
a#4 /app/gptserver/vendor/hyperf/redis/src/Redis.php(47): Hyperf\Pool\Connection->getConnection()
[#5 /app/gptserver/vendor/hyperf/redis/src/RedisProxy.php(32): Hyperf\Redis\Redis->__call()
o#6 /app/gptserver/vendor/hyperf/async-queue/src/Driver/RedisDriver.php(193): Hyperf\Redis\RedisProxy->__call()
y#7 /app/gptserver/vendor/hyperf/async-queue/src/Driver/RedisDriver.php(85): Hyperf\AsyncQueue\Driver\RedisDriver->move()
s#8 /app/gptserver/vendor/hyperf/async-queue/src/Driver/Driver.php(86): Hyperf\AsyncQueue\Driver\RedisDriver->pop()
|#9 /app/gptserver/vendor/hyperf/async-queue/src/Process/ConsumerProcess.php(57): Hyperf\AsyncQueue\Driver\Driver->consume()
{#10 /app/gptserver/vendor/hyperf/process/src/AbstractProcess.php(134): Hyperf\AsyncQueue\Process\ConsumerProcess->handle()
#11 {main}
[WARNING] Get connection failed, try again. RedisException: Connection refused in /app/gptserver/vendor/hyperf/redis/src/RedisConnection.php:268

Stack trace:
U#0 /app/gptserver/vendor/hyperf/redis/src/RedisConnection.php(268): Redis->connect()
p#1 /app/gptserver/vendor/hyperf/redis/src/RedisConnection.php(117): Hyperf\Redis\RedisConnection->createRedis()
m#2 /app/gptserver/vendor/hyperf/redis/src/RedisConnection.php(91): Hyperf\Redis\RedisConnection->reconnect()
q#3 /app/gptserver/vendor/hyperf/pool/src/Connection.php(49): Hyperf\Redis\RedisConnection->getActiveConnection()
a#4 /app/gptserver/vendor/hyperf/redis/src/Redis.php(47): Hyperf\Pool\Connection->getConnection()
[#5 /app/gptserver/vendor/hyperf/redis/src/RedisProxy.php(32): Hyperf\Redis\Redis->__call()
o#6 /app/gptserver/vendor/hyperf/async-queue/src/Driver/RedisDriver.php(193): Hyperf\Redis\RedisProxy->__call()
y#7 /app/gptserver/vendor/hyperf/async-queue/src/Driver/RedisDriver.php(85): Hyperf\AsyncQueue\Driver\RedisDriver->move()
s#8 /app/gptserver/vendor/hyperf/async-queue/src/Driver/Driver.php(86): Hyperf\AsyncQueue\Driver\RedisDriver->pop()
|#9 /app/gptserver/vendor/hyperf/async-queue/src/Process/ConsumerProcess.php(57): Hyperf\AsyncQueue\Driver\Driver->consume()
{#10 /app/gptserver/vendor/hyperf/process/src/AbstractProcess.php(134): Hyperf\AsyncQueue\Process\ConsumerProcess->handle()
#11 {main}
Y[INFO] Crontab task [memberPackageExpired] executed successfully at 2023-07-18 11:00:00.
Y[INFO] Crontab task [memberPackageExpired] executed successfully at 2023-07-18 12:00:00.
Y[INFO] Crontab task [memberPackageExpired] executed successfully at 2023-07-18 13:00:00.
Y[INFO] Crontab task [memberPackageExpired] executed successfully at 2023-07-18 14:00:00.
b[2023-07-18 14:56:20 *27.0]	NOTICE	ProcessFactory::end() (ERRNO 1005): session#21 does not exists
b[2023-07-18 14:56:20 *27.0]	NOTICE	ProcessFactory::end() (ERRNO 1005): session#26 does not exists
b[2023-07-18 14:56:20 *27.0]	NOTICE	ProcessFactory::end() (ERRNO 1005): session#27 does not exists
b[2023-07-18 14:56:20 *27.0]	NOTICE	ProcessFactory::end() (ERRNO 1005): session#25 does not exists
b[2023-07-18 14:56:20 *27.0]	NOTICE	ProcessFactory::end() (ERRNO 1005): session#23 does not exists
b[2023-07-18 14:56:20 *27.0]	NOTICE	ProcessFactory::end() (ERRNO 1005): session#24 does not exists
b[2023-07-18 14:56:22 *27.0]	NOTICE	ProcessFactory::end() (ERRNO 1005): session#28 does not exists
b[2023-07-18 14:56:22 *27.0]	NOTICE	ProcessFactory::end() (ERRNO 1005): session#29 does not exists
b[2023-07-18 14:56:22 *27.0]	NOTICE	ProcessFactory::end() (ERRNO 1005): session#30 does not exists
)[INFO] Process[queue.default.0] stopped.
)[INFO] Process[queue.default.0] stopped.
¬PHP Notice:  Hyperf\Database\Connection::setPdo(): Send of 5 bytes failed with errno=32 Broken pipe in /app/gptserver/vendor/hyperf/database/src/Connection.php on line 648

§Notice: Hyperf\Database\Connection::setPdo(): Send of 5 bytes failed with errno=32 Broken pipe in /app/gptserver/vendor/hyperf/database/src/Connection.php on line 648
b[2023-07-18 14:56:58 *27.0]	NOTICE	ProcessFactory::end() (ERRNO 1005): session#31 does not exists
\PHP Notice:  Unknown: Send of 5 bytes failed with errno=32 Broken pipe in Unknown on line 0

WNotice: Unknown: Send of 5 bytes failed with errno=32 Broken pipe in Unknown on line 0
'[INFO] Process[queue.default.0] start.
'[INFO] Process[queue.default.0] start.
b[2023-07-18 14:57:11 *27.0]	NOTICE	ProcessFactory::end() (ERRNO 1005): session#32 does not exists
b[2023-07-18 14:57:22 *27.0]	NOTICE	ProcessFactory::end() (ERRNO 1005): session#33 does not exists
b[2023-07-18 14:58:23 *27.0]	NOTICE	ProcessFactory::end() (ERRNO 1005): session#34 does not exists

**Comment by irol765** [comment]
新的日志，请看看

**Comment by 0daynick** [comment]
> 新的日志，请看看

环境相关的问题自行进行调试，不做支持。

**Comment by irol765** [comment]
那请给我个方向，目前都是使用大佬提供的手册和介质，我也都没修改过，之前1.2都正常呀

**Comment by 0daynick** [comment]
> 那请给我个方向，目前都是使用大佬提供的手册和介质，我也都没修改过，之前1.2都正常呀

你的错误就如日志所见，redis 连接失败。可以手动访问连接，确保可用。如是 docker-compose 部署可单独重启 gptlink 容器，排除因 gptlink 在 redis 之前启动。或进群寻求帮助。
