### ISSUE TITLE
model表有歧义

### ISSUE THREAD

**Issue by onekb** [gptlink/gptlink#65]
chat_gpt_model是用来放“咒语”的
model模型一般指的是训练好后的文件
更为恰当的 应该命名为“prompt”
希望可以修改下

**Comment by 0daynick** [comment]
> chat_gpt_model是用来放“咒语”的 model模型一般指的是训练好后的文件 更为恰当的 应该命名为“prompt” 希望可以修改下

欢迎PR

**Comment by onekb** [comment]
> > chat_gpt_model是用来放“咒语”的 model模型一般指的是训练好后的文件 更为恰当的 应该命名为“prompt” 希望可以修改下
> 
> 欢迎PR

行

**Comment by 0daynick** [comment]
只是纯粹的为了语义化而语义化，其实不是那么有必要。反而需要去承担因更名导致的所有相关模块的代码逻辑的变更所带来的影响。

**Comment by onekb** [comment]
> 只是纯粹的为了语义化而语义化，其实不是那么有必要。反而需要去承担因更名导致的所有相关模块的代码逻辑的变更所带来的影响。

我这边有个计划，可以让用户自由切换GPT3.5/4.0模型，还可以接入其他LLM厂家的API，这样可能就和model有歧义了
