### ISSUE TITLE
角色分类功能完善,首页功能完善。

### ISSUE THREAD

**Issue by Marks-Jack** [gptlink/gptlink#76]
1.完善角色分类功能，现在如果添加的角色几十个或者上百个，看着就会非常眼花缭乱
2.首页打开直接是新话题页面，建议把所添加的角色放置默认首页。
   2.1 如果用户在当前页面回复，将使用新话题进行对话。
   2.2 用户可直接在首页选择已添加角色的进行对话。

**Comment by 0daynick** [comment]
> 1.完善角色分类功能，现在如果添加的角色几十个或者上百个，看着就会非常眼花缭乱 2.首页打开直接是新话题页面，建议把所添加的角色放置默认首页。 2.1 如果用户在当前页面回复，将使用新话题进行对话。 2.2 用户可直接在首页选择已添加角色的进行对话。

欢迎PR
