### ISSUE TITLE
模型/角色管理优化

### ISSUE THREAD

**Issue by Marks-Jack** [gptlink/gptlink#78]
1.每个不同的角色可以单独设置模型，如果模型留空，则使用全局配置的模型
2.增加角色所属组配置，可设置归属组默认使用的模型
模型优先级配置如下：
单独设置>组配置>全局配置

**Comment by 0daynick** [comment]
> 1.每个不同的角色可以单独设置模型，如果模型留空，则使用全局配置的模型 2.增加角色所属组配置，可设置归属组默认使用的模型 模型优先级配置如下： 单独设置>组配置>全局配置

欢迎PR
