### ISSUE TITLE
ssl证书无法部署

### ISSUE THREAD

**Issue by happy724** [gptlink/gptlink#80]
![image](https://github.com/gptlink/gptlink/assets/122508527/1dd2bc50-1349-4f48-9c88-52bee3478344)
![image](https://github.com/gptlink/gptlink/assets/122508527/79b87a59-7cc4-406a-aa25-a25f9af2c7e7)
![image](https://github.com/gptlink/gptlink/assets/122508527/ceb6257b-90d4-4a43-a88a-fcff8f3dc002)

如图安装证书
![image](https://github.com/gptlink/gptlink/assets/122508527/4543305d-3e20-4eda-aff8-c4b1b12d7470)
https仍然无法连接
![image](https://github.com/gptlink/gptlink/assets/122508527/99f67500-73cf-4c9c-8aa1-60b719054f61)

**Comment by 0daynick** [comment]
> ![image](https://private-user-images.githubusercontent.com/122508527/290115507-1dd2bc50-1349-4f48-9c88-52bee3478344.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3OTk5MjMsIm5iZiI6MTcwNDc5OTYyMywicGF0aCI6Ii8xMjI1MDg1MjcvMjkwMTE1NTA3LTFkZDJiYzUwLTEzNDktNGY0OC05Yzg4LTUyYmVlMzQ3ODM0NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwOVQxMTI3MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYzQ2YTMyZTRjMTdkZjc1OTIxODM2MmZkYzc5OWVkNWQ4M2Q5ZjFkOTY1NDkxN2U1NTA5MzNiMGNjMTgxM2MwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Ylpwisceex8pzfLDZPi14puoWaSxs4cI85KDDKYyWx4) ![image](https://private-user-images.githubusercontent.com/122508527/290115287-79b87a59-7cc4-406a-aa25-a25f9af2c7e7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3OTk5MjMsIm5iZiI6MTcwNDc5OTYyMywicGF0aCI6Ii8xMjI1MDg1MjcvMjkwMTE1Mjg3LTc5Yjg3YTU5LTdjYzQtNDA2YS1hYTI1LWEyNWY5YWYyYzdlNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwOVQxMTI3MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MzkwNjc0MjU4YjMwYTZjZjljZGI4MjY5OWE4NWFmMmRmNTNlZjI3OTUwNjc3MjliYzUzMGUwNjI2YTUwZjA2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.qqq_WAeWqcI_UozhX2wy9y6pZhYefzFSdao1MkaDQfI) ![image](https://private-user-images.githubusercontent.com/122508527/290115363-ceb6257b-90d4-4a43-a88a-fcff8f3dc002.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3OTk5MjMsIm5iZiI6MTcwNDc5OTYyMywicGF0aCI6Ii8xMjI1MDg1MjcvMjkwMTE1MzYzLWNlYjYyNTdiLTkwZDQtNGE0My1hODhhLWZjZmY4ZjNkYzAwMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwOVQxMTI3MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01M2FmMWQwNzRjNWNiYjM1MDNiN2M5NTU4MDQzZjQ3YTRlZjZkZjQwZTM0NjM0Yzc1YWExNDE5OTFiMDhmN2NlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.h6irK-3nwkih8cF6Jt_2yyrBUQQRku26ehetHEW7Bio)
> 
> 如图安装证书 ![image](https://private-user-images.githubusercontent.com/122508527/290114814-4543305d-3e20-4eda-aff8-c4b1b12d7470.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3OTk5MjMsIm5iZiI6MTcwNDc5OTYyMywicGF0aCI6Ii8xMjI1MDg1MjcvMjkwMTE0ODE0LTQ1NDMzMDVkLTNlMjAtNGVkYS1hZmY4LWM0YjFiMTJkNzQ3MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwOVQxMTI3MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03OTFmOWU0NDA0ZmUwNDk0NDY0ZTNhYTkxZWI2Yjk0ZjBkN2NlYWQ3ZjViZmQ1ZDA0ZDk4NDBjOWIyZDQ0Y2QyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.giZZLaiDWHXDoaZQt2GZiSJPB3Gj91CyMi4hEQ2NJfc) https仍然无法连接 ![image](https://private-user-images.githubusercontent.com/122508527/290115113-99f67500-73cf-4c9c-8aa1-60b719054f61.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3OTk5MjMsIm5iZiI6MTcwNDc5OTYyMywicGF0aCI6Ii8xMjI1MDg1MjcvMjkwMTE1MTEzLTk5ZjY3NTAwLTczY2YtNGM5Yy04YWExLTYwYjcxOTA1NGY2MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwOVQxMTI3MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MGEwNDkxMjAxNjFiNjg1ZDc1NmM4ODdjMGQ4OWY5OGJhNmRmMTNiMGJmMTI4ZWRmY2I0YjE2YzEzZDIxZmJkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Qqy0anQUI7hsp10Wn-2CO4pj-b9IMiANCQXugnz5WZ8)

需要重新build再运行
