### ISSUE TITLE
聊天回复有漏字问题？

### ISSUE THREAD

**Issue by godsontop** [gptlink/gptlink#82]
日志：
Warning: Undefined array key "port" in /app/gptserver/app/Base/OpenAi/OpenAIClient.php on line 144
[2024-01-15 16:41:08 *28.0]     NOTICE  ProcessFactory::end() (ERRNO 1005): session#57 does not exists
PHP Warning:  Undefined array key "port" in /app/gptserver/app/Base/OpenAi/OpenAIClient.php on line 144

Warning: Undefined array key "port" in /app/gptserver/app/Base/OpenAi/OpenAIClient.php on line 144
[2024-01-15 16:42:01 *28.0]     NOTICE  ProcessFactory::end() (ERRNO 1005): session#58 does not exists

![Snipaste_2024-01-15_16-44-02](https://github.com/gptlink/gptlink/assets/78685775/adf11f31-efda-405e-bf12-cc3ce28b37d7)
![Snipaste_2024-01-15_16-44-12](https://github.com/gptlink/gptlink/assets/78685775/af888094-6d46-4b59-b425-fa23f5ca1ba9)

**Comment by jacywy** [comment]
同样不定期出现此问题

**Comment by elevenwd** [comment]
问题已修复，请拉取1.3.4版本最新代码和镜像
